import { defineConfig, presetIcons } from 'unocss'

export default defineConfig({
  content: {
    filesystem: ['src/**/*.{ts,vue}'],
  },
  presets: [
    presetIcons({
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
      // @iconify-json/* 的新入口只提供具名导出（icons/info/metadata/chars），不再有 default，
      // presetIcons 的默认加载器因此取不到图标数据并静默产出空 CSS，这里显式声明用到的集合。
      collections: {
        'lucide': () => import('@iconify-json/lucide').then(collection => collection.icons),
        'ri': () => import('@iconify-json/ri').then(collection => collection.icons),
        'svg-spinners': () => import('@iconify-json/svg-spinners').then(collection => collection.icons),
      },
    }),
  ],
  safelist: [
    'i-ri-add-line',
    'i-ri-arrow-down-s-line',
    'i-ri-arrow-right-s-line',
    'i-ri-bar-chart-2-line',
    'i-ri-box-3-line',
    'i-ri-briefcase-4-line',
    'i-ri-brush-line',
    'i-ri-calendar-line',
    'i-ri-checkbox-circle-fill',
    'i-ri-close-line',
    'i-ri-cloud-line',
    'i-ri-code-s-slash-line',
    'i-ri-compass-3-line',
    'i-ri-database-2-line',
    'i-ri-draggable',
    'i-ri-edit-line',
    'i-ri-error-warning-fill',
    'i-ri-external-link-line',
    'i-ri-file-copy-line',
    'i-ri-file-search-line',
    'i-ri-file-text-line',
    'i-ri-flask-line',
    'i-ri-folder-3-line',
    'i-ri-folder-open-line',
    'i-ri-folders-line',
    'i-ri-git-merge-line',
    'i-ri-git-repository-line',
    'i-ri-global-line',
    'i-ri-links-line',
    'i-ri-list-check-3',
    'i-ri-refresh-line',
    'i-ri-more-2-fill',
    'i-ri-node-tree',
    'i-ri-palette-line',
    'i-ri-play-fill',
    'i-ri-question-line',
    'i-ri-rocket-line',
    'i-ri-search-line',
    'i-ri-settings-3-line',
    'i-ri-shield-check-line',
    'i-ri-shield-keyhole-line',
    'i-ri-sparkling-2-line',
    'i-ri-smartphone-line',
    'i-ri-star-fill',
    'i-ri-star-line',
    'i-ri-stack-line',
    'i-ri-stop-fill',
    'i-ri-team-line',
    'i-ri-terminal-box-line',
    'i-ri-terminal-window-line',
    'i-ri-user-line',
    'i-svg-spinners-180-ring-with-bg',
  ],
})
