import { defineConfig, presetIcons } from 'unocss'

export default defineConfig({
  content: {
    filesystem: ['src/**/*.{ts,vue}'],
  },
  presets: [
    presetIcons({
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  safelist: [
    'i-ri-add-line',
    'i-ri-arrow-down-s-line',
    'i-ri-arrow-right-s-line',
    'i-ri-bar-chart-2-line',
    'i-ri-box-3-line',
    'i-ri-brush-line',
    'i-ri-calendar-line',
    'i-ri-checkbox-circle-fill',
    'i-ri-close-line',
    'i-ri-cloud-line',
    'i-ri-code-s-slash-line',
    'i-ri-database-2-line',
    'i-ri-draggable',
    'i-ri-edit-line',
    'i-ri-error-warning-fill',
    'i-ri-file-search-line',
    'i-ri-file-text-line',
    'i-ri-flask-line',
    'i-ri-folder-3-line',
    'i-ri-folders-line',
    'i-ri-global-line',
    'i-ri-loader-4-line',
    'i-ri-more-2-fill',
    'i-ri-node-tree',
    'i-ri-palette-line',
    'i-ri-play-fill',
    'i-ri-rocket-line',
    'i-ri-search-line',
    'i-ri-settings-3-line',
    'i-ri-shield-check-line',
    'i-ri-shield-keyhole-line',
    'i-ri-sparkling-2-line',
    'i-ri-smartphone-line',
    'i-ri-star-fill',
    'i-ri-star-line',
    'i-ri-stack-line',
    'i-ri-stop-fill',
    'i-ri-team-line',
    'i-ri-terminal-box-line',
    'i-ri-terminal-window-line',
  ],
})
