/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocsProjectCard: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.3.0/node_modules/@yunyoujun/docs/client/components/DocsProjectCard.vue')['default']
    DocsProjectList: typeof import('./../../node_modules/.pnpm/@yunyoujun+docs@0.1.14_vite@8.3.0/node_modules/@yunyoujun/docs/client/components/DocsProjectList.vue')['default']
    DownloadPage: typeof import('./theme/components/DownloadPage.vue')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    MarketplacePage: typeof import('./theme/components/MarketplacePage.vue')['default']
  }
}
