#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Craft Hub macOS signing setup"

stage "GitHub CLI access"
say "The wizard writes credentials directly to this repository's GitHub Actions secrets."
if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI is not installed. Install it with: brew install gh"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  step "Run 'gh auth login' in another terminal and authenticate with GitHub."
  pause "Press Enter after GitHub authentication is complete."
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is still not authenticated. Re-run this wizard after 'gh auth login'."
  exit 1
fi
say "GitHub repository: $(gh repo view --json nameWithOwner --jq .nameWithOwner)"
pause "GitHub access is ready. Press Enter to continue."

stage "Create Developer ID Application certificate"
say "This certificate signs Craft Hub for distribution outside the Mac App Store."
say "You need an active Apple Developer Program membership and Account Holder/Admin access."
open_url "https://developer.apple.com/account/resources/certificates/list"
step "If you do not already have a CSR: open Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority."
step "Enter your Apple Developer email and a Common Name, choose 'Saved to disk', then save the .certSigningRequest file."
step "On Apple's Certificates page click + → Developer ID → Developer ID Application."
step "Upload the CSR, download the resulting .cer file, then double-click it to install it in your login keychain."
pause "Press Enter after the certificate appears under Keychain Access → My Certificates."
if ! security find-identity -v -p codesigning | grep -q 'Developer ID Application'; then
  warn "No Developer ID Application identity with a private key was found in your keychain."
  warn "Make sure the certificate is expanded under 'My Certificates' and shows its private key."
  exit 1
fi
say "Developer ID Application identity found."

stage "Export signing certificate"
say "Export the certificate and its private key as a password-protected PKCS#12 file."
step "In Keychain Access → My Certificates, expand 'Developer ID Application'."
step "Select the certificate and private key, right-click, then choose Export 2 items."
step "Save as Personal Information Exchange (.p12) and assign a strong one-time password."
ask MACOS_CERTIFICATE_PATH "Paste the absolute path to the exported .p12 file:"
if [[ ! -f "$MACOS_CERTIFICATE_PATH" ]]; then
  warn "Certificate file does not exist: $MACOS_CERTIFICATE_PATH"
  exit 1
fi
ask_secret MACOS_CERTIFICATE_PASSWORD "Enter the .p12 export password:"
if ! MACOS_CERTIFICATE_PASSWORD="$MACOS_CERTIFICATE_PASSWORD" \
  openssl pkcs12 -in "$MACOS_CERTIFICATE_PATH" -passin env:MACOS_CERTIFICATE_PASSWORD -noout >/dev/null 2>&1; then
  warn "The .p12 file or password could not be validated."
  exit 1
fi
MACOS_CERTIFICATE_BASE64=$(base64 < "$MACOS_CERTIFICATE_PATH" | tr -d '\r\n')
set_secret MACOS_CERTIFICATE_BASE64 "$MACOS_CERTIFICATE_BASE64"
set_secret MACOS_CERTIFICATE_PASSWORD "$MACOS_CERTIFICATE_PASSWORD"

stage "Create notarization API key"
say "Apple's notary service scans the signed app and issues the Gatekeeper ticket."
say "Use a Team Key with the App Manager role; individual keys cannot use notarytool."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "If prompted, the Account Holder must first request App Store Connect API access."
step "Open Team Keys, click Generate API Key (+), name it 'Craft Hub Notarization', and select App Manager access."
step "Generate the key, copy its Key ID and the page's Issuer ID, then download AuthKey_<KEY_ID>.p8."
warn "Apple allows the private .p8 key to be downloaded only once. Keep a secure backup."
ask APPLE_API_KEY_ID "Paste the Key ID:"
ask APPLE_API_ISSUER_ID "Paste the Issuer ID:"
ask APPLE_API_KEY_PATH "Paste the absolute path to the downloaded .p8 file:"
if [[ ! -f "$APPLE_API_KEY_PATH" ]]; then
  warn "API key file does not exist: $APPLE_API_KEY_PATH"
  exit 1
fi
if ! grep -q 'BEGIN PRIVATE KEY' "$APPLE_API_KEY_PATH"; then
  warn "The selected file does not look like an App Store Connect .p8 private key."
  exit 1
fi
APPLE_API_KEY_BASE64=$(base64 < "$APPLE_API_KEY_PATH" | tr -d '\r\n')
set_secret APPLE_API_KEY_BASE64 "$APPLE_API_KEY_BASE64"
set_secret APPLE_API_KEY_ID "$APPLE_API_KEY_ID"
set_secret APPLE_API_ISSUER_ID "$APPLE_API_ISSUER_ID"

stage "Verify GitHub secrets"
say "The Release workflow requires all five secrets before it can sign and notarize both builds."
missing=0
for secret_name in \
  MACOS_CERTIFICATE_BASE64 \
  MACOS_CERTIFICATE_PASSWORD \
  APPLE_API_KEY_BASE64 \
  APPLE_API_KEY_ID \
  APPLE_API_ISSUER_ID; do
  if gh secret list --json name --jq '.[].name' | grep -qx "$secret_name"; then
    say "✓ $secret_name"
  else
    warn "Missing GitHub secret: $secret_name"
    missing=1
  fi
done
if (( missing )); then
  warn "One or more secrets are missing. Fix them before pushing a release tag."
  exit 1
fi
say "The next v* tag will build, sign, notarize, staple, verify, and upload arm64 and x64 ZIP files."
pause "Press Enter to finish."

finish
